# Generated by Django 5.2.5 on 2025-08-23 22:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('has_ended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['is_active', 'start_date', 'end_date'], name='election_el_is_acti_17f51b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ElectionLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(choices=[('president', 'President'), ('state', 'State'), ('course', 'Course')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'indexes': [models.Index(fields=['code'], name='election_el_code_ed5cf2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('gender_restriction', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('any', 'Any')], default='any', max_length=10)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('election_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.electionlevel')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.state')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('platform', models.TextField(blank=True)),
                ('vote_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.election')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.position')),
            ],
        ),
        migrations.CreateModel(
            name='VoterToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.election')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.election')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.votertoken')),
            ],
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['election_level', 'state', 'course'], name='election_po_electio_4b8711_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('election_level', 'title', 'gender_restriction', 'state', 'course')},
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['election', 'position'], name='election_ca_electio_1af40c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('user', 'election', 'position')},
        ),
        migrations.AddIndex(
            model_name='votertoken',
            index=models.Index(fields=['token'], name='election_vo_token_7bf182_idx'),
        ),
        migrations.AddIndex(
            model_name='votertoken',
            index=models.Index(fields=['election', 'is_used'], name='election_vo_electio_7196fb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='votertoken',
            unique_together={('user', 'election')},
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('token', 'election')},
        ),
    ]
