# Generated by Django 6.0.3 on 2026-03-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('voter', 'Voter'), ('candidate', 'Candidate'), ('class_leader', 'Class Leader'), ('commissioner', 'Commissioner'), ('observer', 'Election Observer')], default='voter', help_text="User's role in the election system", max_length=20),
        ),
    ]
